elastic/elasticsearch-java

- java-client/build.gradle.kts
Changes the directory structure of the jar from
```
META-INF/
META-INF/MANIFEST.MF
META-INF/./
META-INF/./LICENSE.txt
META-INF/./NOTICE.txt
```
to
```
META-INF/
META-INF/MANIFEST.MF
META-INF/NOTICE.txt
META-INF/LICENSE.txt
```
Closes #5
> Fix META-INF path for LICENSE.TXT and NOTICE.TXT

- .ci/Dockerfile
Copy the config directory into the docker image used by CI. Without this
the build command used by the unified build process fails.
```
env DEPENDENCIES_REPORTS_DIR=$PWD \
DEPENDENCIES_REPORT=dependencies-report.csv \
.ci/make.sh assemble 8.0.0-SNAPSHOT
```
> Copy config into ci docker image

- README.md
> Amend compatibility matrix

- .github/workflows/checkstyle.yml
The AdoptOpenJDK has been discontinued Since July 2021. When using Zulu you get all the latest updated builds for all versions of OpenJDK. Also, I've added a matrix to later add JDK 17 (next LTS release). Gradle currently does not support JDK early access releases.
> Using Temurin builds of OpenJDK in GH actions

- docs/installation.asciidoc
This PR fixes the following build error in https://github.com/elastic/elasticsearch/pull/77747:
> 14:42:54 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/java-rest/master/installation.html contains broken links to:
14:42:54 INFO:build_docs:   - en/elasticsearch/client/java-rest/current/java-rest-low.htm8l
> [DOCS] Fixes typo

- docs/connecting.asciidoc
- docs/index.asciidoc
- docs/installation.asciidoc
This PR backports the changes of the following commits to the 7.x branch:
[DOCS] Adds intro text to the index file, changes snippet attributes #17
> [7.x][DOCS] Adds intro text to the index file, changes snippet attributes

- docs/index.asciidoc
This PR removes the `partintro` attribute from the index file of the docs.
Related to https://github.com/elastic/docs/pull/2230
> [DOCS] Removes partintro from book index

- docs/index.asciidoc
This PR backports the changes of the following commit to the 7.x branch: https://github.com/elastic/elasticsearch-java/pull/22
> [7.x][DOCS] Removes partintro from book index

- docs/index.asciidoc
- docs/introduction.asciidoc
This PR removes content from the index file and changes the book title.
> [DOCS] Removes content from index and changes book title

- docs/installation.asciidoc
This PR updates Maven coordinates to reflect the publication to Maven Central.
> Update Maven coordinates

- docs/connecting.asciidoc
- docs/installation.asciidoc
- docs/introduction.asciidoc
Correct the docs stability disclaimer by promoting the client to `beta`.
> Promote client stability in docs

- docs/introduction.asciidoc
This PR updates the link in the Intro section to point to the new LLRC section in the Java API book.
[Introduction](https://elasticsearch-java_29.docs-preview.app.elstc.co/guide/en/elasticsearch/client/java-api-client/master/introduction.html)
> [DOCS] Updates the link in Introduction that points to LLRC

- docs/installation.asciidoc
There are two `Compatibility` sections in the docs on 7.16: one in the Introduction page and one in the Installation page. To be 7.16 in line with main, this PR removes the duplication from the Installation page.
> [7.16][DOCS] Removes duplicated compatibility section

- docs/api-conventions.asciidoc
- docs/connecting.asciidoc
- docs/index-local.asciidoc
- docs/index.asciidoc
- docs/installation.asciidoc
- docs/introduction.asciidoc
- docs/local/README.md
- docs/local/elasticsearch/docs/java-rest/low-level/index.asciidoc
- docs/local/index.asciidoc
- docs/migrate.asciidoc
- java-client/src/test/java/co/elastic/clients/documentation/ApiConventionsTest.java
Update/cleanup documentation and refactor code examples as included sections of test code, so that code snippets in the docs are compiled and tested.
> [docs] Update with the latest changes and use compilable examples

- java-client/src/main/java/co/elastic/clients/json/LazyDeserializer.java
- java-client/src/test/java/co/elastic/clients/json/LazyDeserializerTest.java
> Fix race condition in LazyDeserializer initialization

- java-client/build.gradle.kts
With the move from `javax.json` to `jakarta.json`, the Glassfish reference implementation of JSON-P has been updated to implement interfaces from `jakarta.json` but its class names haven't changed, causing conflicts in environments where the `javax.json` variant is present such as JEE8.
The `jakarta.json` variant of Glassfish is now available under a new name, [Eclipse Parsson](https://github.com/eclipse-ee4j/parsson). This PR updates the dependencies to replace Glassfish with Parsson.
Fixes #55
> Change the JSON-P implementation from Glassfish to Parsson

- docs/index-local.asciidoc
- docs/index.asciidoc
- docs/javadoc-and-source.asciidoc
New docs section linking to javadocs and source code.
> Add links to javadoc and source code

- docs/index-local.asciidoc
- docs/index.asciidoc
- docs/javadoc-and-source.asciidoc
Fixes javadoc links for Java API client, Low Level Rest Client and Sniffer by using the use the `source_branch` attribute provided by the build system.
Fixes #83
> Fix javadoc links, using branch information provided by the doc build system

- java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientTransport.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java
> Add workaround for missing header in snapshot request

- java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/spec_issues/SpecIssuesTest.java
- java-client/src/test/resources/co/elastic/clients/elasticsearch/spec_issues/issue-0087-request.json
- java-client/src/test/resources/co/elastic/clients/elasticsearch/spec_issues/issue-0087-response.json
- java-client/src/test/resources/co/elastic/clients/elasticsearch/spec_issues/issue-0088-response.json
Backports the following commits to 8.0:
- Add tests for #87 and #88 (#126)
> [8.0] Add tests for #87 and #88 (#126)

- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/json/jackson/JacksonMapperTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/ModelTestCase.java
Creating Jackson's parser factory from the object mapper makes this mapper available via `JsonParser.getCodec()`.
Fixes #120
> Make Jackson object mapper available from custom deserializers

- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/json/jackson/JacksonMapperTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/ModelTestCase.java
Backports the following commits to 8.0:
- Make Jackson object mapper available from custom deserializers (#129)
> [8.0] Make Jackson object mapper available from custom deserializers (#129)

- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/json/jackson/JacksonMapperTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/ModelTestCase.java
Backports the following commits to 7.17:
- Make Jackson object mapper available from custom deserializers (#129)
> [7.17] Make Jackson object mapper available from custom deserializers (#129)

- java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestServer.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/spec_issues/SpecIssuesTest.java
> Add tests for compact ErrorCause

- CHANGELOG.md
- docs/index.asciidoc
- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
- docs/release-notes/breaking-change-policy.asciidoc
This PR adds release notes for the 7.17 branch. It will be "up-ported" to 8.0 and 8.1 with additional release notes added for these versions.
An important part of these docs is about documenting the breaking changes and explaining the breaking change policy.
> Add release notes

- config/forbidden-apis.txt
- java-client/build.gradle.kts
- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonProvider.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JsonValueParser.java
- java-client/src/main/java/co/elastic/clients/json/jsonb/JsonbJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/util/AllowForbiddenApis.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/ParsingTests.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/containers/SomeUnionTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/inheritance/InheritanceTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/json/JsonpUtilsTest.java
Fixes #163
Calling `JsonProvider.provider()` invokes `ServiceLoader` that tries to find an implementation from the current thread's context classloader. In some environments where the context classloader isn't correctly set, this can cause a failure to find an implementation, even if the deployment was otherwise correct.
This PR enhances the provider lookup when the standard method fails by first trying to find an implementation in the Java client's classloader, and else in the JsonP SPI library's classloader.
It also introduces the [forbidden-apis](https://github.com/policeman-tools/forbidden-apis/) build plugin to make sure we will not inadvertently reintroduce calls to `JsonProvider.provider()`.
> Fallback to current class if loading a Jsonp provider using ServiceLoader fails

- docs/installation.asciidoc
- docs/introduction.asciidoc
- java-client/build.gradle.kts
Updates the URL to the JSON-B specification. The previous one was abandoned as part of the move from JavaEE to JakartaEE.
Also fixes #148 (typo).
> Fix jsonb url

- docs/installation.asciidoc
Explain how to override Spring Boot's dependency override mechanism that is causing `java.lang.ClassNotFoundException: jakarta.json.spi.JsonProvider` that were reported a number of times.
Related: #79
> Add docs about Spring and jakarta-json

- docs/index.asciidoc
- docs/loading-json.asciidoc
Only include documentation of the `withJson` feature in versions `8.1.1`+ and `7.1.2`+
> Include withJson docs only in correct versions

- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/json/JsonpUtilsTest.java
Revisiting the serialization of primitive number values with `NaN` or `Infinity` used to identify missing values.
Reported by @dadoonet
> Fix serialization of NaN/Infinite/Min/Max values

- docs/migrate.asciidoc
- java-client/src/test/java/co/elastic/clients/documentation/MigrateHlrcTest.java
Explain HLRC's compatibility mode so that a `7.17` client works with a `8.x` cluster, refactor code sample.
> Hrlc compat doc

- java-client/src/main/java/co/elastic/clients/json/DelegatingJsonParser.java
- java-client/src/main/java/co/elastic/clients/json/ExternallyTaggedUnion.java
- java-client/src/main/java/co/elastic/clients/json/JsonEnum.java
- java-client/src/main/java/co/elastic/clients/json/JsonLocationImpl.java
- java-client/src/main/java/co/elastic/clients/json/JsonpDeserializer.java
- java-client/src/main/java/co/elastic/clients/json/JsonpDeserializerBase.java
- java-client/src/main/java/co/elastic/clients/json/JsonpMapperBase.java
- java-client/src/main/java/co/elastic/clients/json/JsonpMappingException.java
- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/main/java/co/elastic/clients/json/NamedDeserializer.java
- java-client/src/main/java/co/elastic/clients/json/ObjectDeserializer.java
- java-client/src/main/java/co/elastic/clients/json/UnionDeserializer.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/containers/SomeUnionTest.java
- java-client/src/test/java/co/elastic/clients/json/JsonpMappingExceptionTest.java
Adds a new `JsonpMappingException` that is thrown by the JSON mapping framework instead of a raw `JsonParsingException`. It provides detailed information on the context where the error happened: object class, JSON path and location in the input.
Example error message: `Error deserializing co.elastic.clients.elasticsearch.core.search.Hit: java.lang.NumberFormatException: For input string: "abc" (JSON path: hits.hits[1]._score) (line no=1, column no=491, offset=490)`
> Add mapping exception with JSON path and location

- docs/_releases.asciidoc
This PR addresses the following documentation build errors:
> 11:24:06 INFO:build_docs:ERROR building Java Client version 7.17
> ...
> 11:24:06 INFO:build_docs:
11:24:06 INFO:build_docs:asciidoctor: WARNING: invalid reference: loading-json
11:24:06 INFO:build_docs:
11:24:06 INFO:build_docs:Child exited with 255 at lib/ES/Util.pm line 666.
> [DOCS] Add 7.17.3 to conditional attributes

- docs/getting-started/migrate-hlrc.asciidoc
Make it more explicit that HLRC `7.x` can be used with Java API client `8.x`.
> Explain mixed versions of HLRC and Java API client

- docs/getting-started/installation.asciidoc
Refactor installation documentation about `ClassNotFoundException: jakarta.json.spi.JsonProvider` to make it less specific to Spring Boot (also happens with Helidon, see #227)
> Refactor docs for JsonProvider error

- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/json/JsonpUtilsTest.java
Follow-up to #269.
Elasticsearch API objects can be quite large. In order to avoid using too much memory when calling `toString()` on API objects (and filling up the logs if they end up there), the resulting string is limited, with a default limit of 10k characters. This limit can be changed globally.
> Limit the size of toString() to a configurable limit

- java-client/src/main/java/co/elastic/clients/elasticsearch/_types/Refresh.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/_types/mapping/DynamicMapping.java
- java-client/src/main/java/co/elastic/clients/json/JsonEnum.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/EnumTest.java
Add a specific JSON (de)serialization for enums that have `true` and `false` values. These used to be boolean properties that evolved into enums to handle more than two states.
Elasticsearch accepts their JSON boolean representation in requests and some tools/products expect them to be serialized as JSON booleans.
Fixes #139
> Handle enums that have true/false values as booleans

- docs/troubleshooting/index.asciidoc
- docs/troubleshooting/serialize-without-typed-keys.asciidoc
- java-client/src/main/java/co/elastic/clients/json/ExternallyTaggedUnion.java
- java-client/src/main/java/co/elastic/clients/json/JsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/JsonpMapperBase.java
- java-client/src/main/java/co/elastic/clients/json/JsonpMapperFeatures.java
- java-client/src/main/java/co/elastic/clients/json/SimpleJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/jsonb/JsonbJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/util/WithJsonObjectBuilderBase.java
- java-client/src/test/java/co/elastic/clients/documentation/troubleshooting/TroubleShootingTests.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/TypedKeysTest.java
Fixes #306
Adds a feature in `JsonpMapper` that allows serializing aggregation and suggestion results using only names as keys and not [typed keys](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html#return-agg-type) (`type#name`), which is what the Java client needs to correctly deserialize these data structures.
This is useful when the Java API client is used as a search front-end to ES and results are serialized back to application clients, who may not expect nor understand the `type#name` format.
> Allow serializing aggregations without typed keys

- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpGenerator.java
- java-client/src/test/java/co/elastic/clients/json/jackson/JacksonJsonpGeneratorTest.java
Fixes #165: a bug in boolean serialization, and adds tests.
The buggy method is never called by the Java API client, but its presence may have caused issues in other uses of the Jackson implementation of `JsonGenerator`.
> Fix booleans in JacksonJsonpGenerator and add tests

- java-client/src/test/java/co/elastic/clients/transport/endpoints/BooleanEndpointTest.java
Fixes `BooleanEndpoint` that incorrectly assumed that requests do not have a body, while `LogstashClient.putPipeline()` and `SecurityClient.samlCompleteLogout()` do have bodies.
Reported in https://discuss.elastic.co/t/java-client-put-logstash-pipeline/309345
> Boolean response endpoints can have a request body

- java-client/src/main/java/co/elastic/clients/ApiClient.java
- java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientOptions.java
- java-client/src/main/java/co/elastic/clients/util/VisibleForTesting.java
- java-client/src/test/java/co/elastic/clients/transport/RequestOptionsTest.java
- java-client/src/test/java/co/elastic/clients/transport/rest_client/RestClientOptionsTest.java
This fixes `RestClientOptions` to ensure that built-in headers (`Accept` and the `X-elastic-client-meta` telemetry header) are always present, even when instantiating the transport with custom `RequestOptions`.
Also ensures `ElasticsearchClient._transportOptions()` is never `null` by falling back to the transport's options.
Fixes #377.
> Fix RestClientOptions building to not lose builtin headers

- java-client/build.gradle.kts
- java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestServer.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/spec_issues/SpecIssuesTest.java
> [7.17] Update to latest API spec, update ES test server to use SSL (#384)

- docs/getting-started/connecting.asciidoc
- java-client/src/main/java/co/elastic/clients/transport/TransportUtils.java
- java-client/src/test/java/co/elastic/clients/documentation/getting_started/ConnectingTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestServer.java
- java-client/src/test/java/co/elastic/clients/transport/TransportUtilsTest.java
Add the `TransportUtils` with helper methods to easily create an `SSLContext` from either a pem-encoded certificate file or a certificate fingerprint. Both are provided by Elasticsearch when security is enabled (the default since version 8.0).
Also add documentation on setting up encrypted communications using these methods.
> Add SSL setup helper class and documentation

- java-client/src/main/java/co/elastic/clients/transport/endpoints/BinaryEndpoint.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/BinaryResponse.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/EndpointBase.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/SimpleJsonEndpoint.java
- java-client/src/main/java/co/elastic/clients/transport/rest_client/HttpClientBinaryResponse.java
- java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientTransport.java
Adds a new `BinaryResponse` that provides an input stream on the http response body.
Will fix #38 after code-generation.
> Add support for binary endpoints

- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
The JacksonJsonpMapper has a public constructor that takes in a user provided ObjectMapper to allow customization for serialization and deserialization.  The constructor can be misleading since it overrides two configurations to disable pretty print and disregard null values on serialization.  As far as I can tell, there is no other way to modify the ObjectMapper configuration other than through the constructor.
The proposal is that these configurations be moved to the default constructor.  This allows users with no preference to take the default configuration, but if custom configuration is desired a user can provide the ObjectMapper.  A few advantages to this strategy:
1. Default constructor still provides desired default configuration
2. Provides more flexibility of configuration to …
> Allow JacksonJsonpMapper user provided ObjectMapper to maintain configuration

- java-client/build.gradle.kts
- java-client/src/main/java/co/elastic/clients/ApiClient.java
- java-client/src/main/java/co/elastic/clients/json/DelegatingJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/JsonData.java
- java-client/src/main/java/co/elastic/clients/json/JsonDataImpl.java
- java-client/src/main/java/co/elastic/clients/json/JsonpDeserializer.java
- java-client/src/main/java/co/elastic/clients/json/JsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/JsonpMapperBase.java
- java-client/src/main/java/co/elastic/clients/json/SimpleJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/jsonb/JsonbJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/util/MissingRequiredPropertyException.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/json/JsonpMapperTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/ModelTestCase.java
Adds support for `java.lang.reflect.Type` in deserializers to allow mapping types with generic parameters. This comes in addition to methods with a `Class<T>` parameter that are kept as is, as they allow better type inference by the compiler when using non-parameterized types.
The endpoint methods will have additional overloaded methods using `Type` in the next code generation.
Fixes #118
> Add Type in addition to Class to map types with generic parameters

- java-client/src/main/java/co/elastic/clients/json/JsonDataImpl.java
Fixes #424
`JsonpMapper`s can require generators to have been created by them (e.g. `JacksonJsonpMapper`), so we should make sure to not mix mapper types when serializing `JsonData`.
Instanciating a `JsonData` with its mapper is of little use, if useful at all, and will be deprecated in 8.6 and removed in a later version.
> Do not mix mapper types in JsonData serialization

- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/test/java/co/elastic/clients/json/JsonpUtilsTest.java
Since the result of `JsonProvider.provider()` is based on the classpath hierarchy, it can be cached. And actually should, as indicated in the javadoc for this method.
Fixes #479, will be included in the next 8.6 and 7.17 patch releases.
> Cache the result of `JsonProvider.provider()`

- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/test/java/co/elastic/clients/json/JsonpUtilsTest.java
> [8.6] Cache the result of `JsonProvider.provider()` (#485)

- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/test/java/co/elastic/clients/json/JsonpUtilsTest.java
> [7.17] Cache the result of `JsonProvider.provider()` (#485)

- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/main/java/co/elastic/clients/json/LookAheadJsonParser.java
- java-client/src/main/java/co/elastic/clients/json/UnionDeserializer.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpParser.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/VariantsTest.java
- java-client/src/test/java/co/elastic/clients/json/JsonpMappingExceptionTest.java
- java-client/src/test/java/co/elastic/clients/json/jackson/JacksonJsonpParserTest.java
JSON deserialization requires to look ahead in JSON objects on two occasions:
* for polymorphic types that are distinguished by their type property (i.e. a property inside the JSON object). An example is the `Property` type, whose variant is defined by the inner `type` property.
* for some types with variants that can be disambiguated by looking at the structure of the JSON objects. The variants do not have the same properties, and inspecting the properties allows knowing what is the actual variant that has to be deserialized. An exemple is the items of a multisearch response, that can be either errors if the `error` property is present and a successful result if the `took`, `hits` or a number of other properties are present.
The JSON-P API doesn't offer a way to buffer JSON events and …
> Add buffered lookahead for Jackson

- java-client/src/main/java/co/elastic/clients/elasticsearch/core/CreateRequest.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/core/IndexRequest.java
- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/main/java/co/elastic/clients/transport/Endpoint.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/BinaryEndpoint.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/BooleanEndpoint.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/DelegatingJsonEndpoint.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/EndpointBase.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/SimpleEndpoint.java
- java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientTransport.java
- java-client/src/main/java/co/elastic/clients/util/BinaryData.java
- java-client/src/main/java/co/elastic/clients/util/ByteArrayBinaryData.java
- java-client/src/main/java/co/elastic/clients/util/ContentType.java
- java-client/src/test/java/co/elastic/clients/documentation/usage/IndexingBulkTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java
PR #474 added a `BinaryData` class used to pre-serialize documents in bulk requests in order to evaluate their size.
This PR extends the usage of `BinaryData` to API requests whose body is an application-provided object. These are the `create` and `index` ingestion endpoints, in addition to `bulk`. This allows providing JSON data as a binary blob without incurring the cost of parsing and reserializing with no additional processing.
> Allow unparsed binary data to be used for ingestion

- java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/FnCondition.java
> [7.17] Re-evaluate predicate in FnCondition.whenReadyIf as the predicate may have changed while awaiting the condition (#502)

- java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/FnCondition.java
> [8.7] Re-evaluate predicate in FnCondition.whenReadyIf as the predicate may have changed while awaiting the condition (#502)

- java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngester.java
Adds additional properties to `BulkIngester` that expose the current state of internal queues: pending requests, their size, and in flight requests.
Fixes #483
> Expose additional BulkIngester metrics

- java-client/src/main/java/co/elastic/clients/elasticsearch/_types/analysis/Analyzer.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/VariantsTest.java
If `type` isn't specified, this is a `CustomAnalyzer`.
Fixes #392
> Add default variant to Analyzer

- .github/workflows/backport.yml
- java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientOptions.java
corrected the sequence for the CLIENT META VALUE sequence as mentioned in the description from the following link
Closes https://github.com/elastic/elasticsearch-java/issues/334
> Reorder key-values in meta header to match other clients #334

- java-client/src/main/java/co/elastic/clients/json/BufferingJsonParser.java
- java-client/src/main/java/co/elastic/clients/json/JsonBuffer.java
- java-client/src/main/java/co/elastic/clients/json/JsonData.java
- java-client/src/main/java/co/elastic/clients/json/JsonDataImpl.java
- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonBuffer.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonProvider.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpParser.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/ModelTestCase.java
- java-client/src/test/java/co/elastic/clients/json/JsonDataTest.java
This PR adds a `BufferingJsonParser` interface that a JSON parser can implement to provide an implementation of `JsonData` based on a JSON event buffer, instead of a materialized `JsonValue`.
This brings some important performance and memory usage improvements when the `JsonData` data is later deserialized into an application object, or even a primitive type.
Fixes #548, and will be part of version 8.8.0.
> Add buffered JsonData implementation for Jackson

- java-client/src/main/java/co/elastic/clients/transport/endpoints/EndpointBase.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/SimpleEndpoint.java
- java-client/src/test/java/co/elastic/clients/transport/endpoints/EndpointBaseTest.java
Rewrite `EndpointBase.pathEncode`:
* remove dependency on Apache httpclient. Dependencies on that library are now limited to `transport.rest_client` since this transport is based on Apache httpclient.
* speed up path encoding, as this function only needs to encode a path segment and not a list of segments like the one provided by Apache httpclient.
> Speed up URL path encoding and remove dependency on httpclient

- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/test/java/co/elastic/clients/json/JsonpUtilsTest.java
Remove spurious `startObject` event emitted in `JsonpUtils.copy()` when traversing an array and add a test.
Fixes #591
> Fix spurious JSON event emitted by JsonpUtils.copy()

- java-client/src/main/java/co/elastic/clients/elasticsearch/core/DeleteByQueryResponse.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/doc-files/api-spec.html
Code generation following the fix in the API specification https://github.com/elastic/elasticsearch-specification/pull/2147
Fixes #413
> Throttling info in DeleteByQueryResponse is optional

- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestServer.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/spec_issues/SpecIssuesTest.java
- java-client/src/test/java/co/elastic/clients/json/JsonpUtilsTest.java
Backport #597 to branch 7.17
Fixes #574
> [7.17] Fix spurious JSON event emitted by JsonpUtils.copy()

- docs/index-custom-title-page.html
This PR temporarily redirects the get started button on the landing page to point to the `Introduction` section. Unblocks https://github.com/elastic/elasticsearch-java/pull/621.
As https://github.com/elastic/elasticsearch-java/pull/617 changed the page title and ID of the previous getting started page and renamed it to Setup, the links that point to that page on the `/current/` branch will be broken after the [backport PR](https://github.com/elastic/elasticsearch-java/pull/621) on 8.8 (the current branch) is merged. The following branches are affected: `main`, `8.9`, `8.8`, `8.7`. However, the 8.8 backport PR already contains the fix which makes the backport of this PR to 8.8 unnecessary.
After this PR is merged and backported all the way down to 8.7 (except 8.8), the backport PR – …
> [DOCS] Temporarily redirect getting started button link on landing page

- README.md
This PR adds links to the different sections of the README file that point to the corresponding section of the getting started page. This way only the getting started documentation needs to be maintained and it will be the source of truth.
> [DOCS] Restructures repo README

- docs/troubleshooting/index.asciidoc
- docs/troubleshooting/no-such-method-request-options.asciidoc
Add a troubleshooting item related to rest-client version mismatch that happens notably when using an outdated version of the Spring Boot Plugin
> Add docs for Exception caused by rest-client version mismatch

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.10`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#668)](https://github.com/elastic/elasticsearch-java/pull/668)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [8.10] [DOCS] Fix `welcome-to-elastic` link (#668)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.9`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#668)](https://github.com/elastic/elasticsearch-java/pull/668)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [8.9] [DOCS] Fix `welcome-to-elastic` link (#668)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.8`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#668)](https://github.com/elastic/elasticsearch-java/pull/668)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [8.8] [DOCS] Fix `welcome-to-elastic` link (#668)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.7`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#668)](https://github.com/elastic/elasticsearch-java/pull/668)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [8.7] [DOCS] Fix `welcome-to-elastic` link (#668)

- java-client-serverless/docs/getting-started.mdx
Verified with a local rendering of docs.
> Fill the blanks in the Serverless getting started

- docs/troubleshooting/index.asciidoc
- docs/troubleshooting/io-reactor-errors.asciidoc
- java-client/build.gradle.kts
- java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientOptions.java
- java-client/src/main/java/co/elastic/clients/transport/rest_client/SafeResponseConsumer.java
- java-client/src/test/java/co/elastic/clients/transport/rest_client/SafeResponseConsumerTest.java
Adds a wrapper around the `RestClient`'s default response consumer so that any `Error` happening there (such as OOME) is reported to the application and doesn't crash the Apache http-client library's reactor.
This should avoid I/O reactor related errors, such as `I/O reactor terminated abnormally`.
Also add troubleshooting documentation for users of previous versions, and users using `RestClient` directly.
> Add protection for the I/O reactor and troubleshooting docs

- java-client-serverless/build.gradle.kts
- java-client/build.gradle.kts
- java-client/src/main/java/co/elastic/clients/transport/rest_client/SafeResponseConsumer.java
We used rest-client version 7.x for compilation in the early days of version 8. Time to update do a recent version.
> Update rest-client version

- java-client-serverless/src/main/java/co/elastic/clients/elasticsearch/ElasticsearchClient.java
- java-client/src/main/java/co/elastic/clients/util/DuplicateResourceFinder.java
- java-client/src/test/java/co/elastic/clients/util/DuplicateResourceFinderTest.java
- java-client/src/test/java/com/fasterxml/jackson/databind/ext/CoreXMLSerializers.java
The Stack ("classic") and Serverless Elasticsearch will be different artifacts but will contain classes with the same name. This PR ensures only one `ElasticsearchClient` exists in the classpath and if not provides detailed information about the conflicting sources.
> Add duplicate class check

- README.md
- docs/introduction.asciidoc
This PR adds a compatibility matrix to the Introduction section of the Java book and the repo README.
[Version compatibility](https://elasticsearch-java_bk_749.docs-preview.app.elstc.co/guide/en/elasticsearch/client/java-api-client/master/introduction.html#_elasticsearch_server_compatibility_policy)
> [DOCS] Adds compatibility matrix to docs and README

- java-client-serverless/src/main/java/co/elastic/clients/elasticsearch/_types/ElasticsearchException.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/_types/ElasticsearchException.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/_types/FieldValue.java
- java-client/src/main/java/co/elastic/clients/json/BufferingJsonGenerator.java
- java-client/src/main/java/co/elastic/clients/json/BufferingJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/DelegatingJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/JsonpDeserializer.java
- java-client/src/main/java/co/elastic/clients/json/JsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/JsonpMapperBase.java
- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpGenerator.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/transport/ElasticsearchTransportBase.java
- java-client/src/main/java/co/elastic/clients/transport/Endpoint.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/BinaryDataResponse.java
- java-client/src/main/java/co/elastic/clients/util/ByteArrayBinaryData.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestServer.java
- java-client/src/test/java/co/elastic/clients/json/jackson/JacksonMapperTest.java
- java-client/src/test/java/co/elastic/clients/testkit/MockHttpClient.java
This PR adds a number of improvements and bugfixes to the JSON and utility classes:
JSON framework:
* A new `BufferingJsonpMapper` allows the creation of `JsonGenerator` that store JSON events in a buffer that can be replayed. This is useful to efficiently create synthetic JSON documents.
* An additional `JsonpMapper.deserialize` method variant accepts the current JSON event. Fixes #741
* The Jackson implementation of `JsonpMapper` now enables the `ACCEPT_SINGLE_VALUE_AS_ARRAY` deserialization feature. This allows single values in a JSON stream to be considered as a single-value collection.
API & transport framework:
* `ElasticsearchException` now holds the low level http response, so that the application can inspect the details of the error.
* Endpoints now have a `call` methods, to make …
> Add misc improvements to the framework

- docs/getting-started.asciidoc
- docs/setup/installation.asciidoc
- example-transports/build.gradle.kts
- java-client-serverless/build.gradle.kts
- java-client-serverless/docs/getting-started.mdx
- java-client/build.gradle.kts
Update to the latest Jackson version. It is still an optional dependency that users have to add to their project to use the `JacksonJsonpMapper`.
> Update Jackson version

- java-client/src/main-flavored/java/co/elastic/clients/elasticsearch/_helpers/esql/EsqlHelper.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/esql/ElasticsearchEsqlAsyncClient.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/esql/ElasticsearchEsqlClient.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/esql/EsqlVersion.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/esql/QueryRequest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestServer.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/esql/EsqlAdapterEndToEndTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/esql/EsqlVersionTest.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/spec_issues/SpecIssuesTest.java
Starting with version 8.14, ES|QL requires a query language version to be sent in requests. Currently there's only one version, which will be used as the default version for all 8.x versions of Elasticsearch, even if new versions of ES|QL versions are added before Elasticsearch 9.0 is released.
If new ES|QL versions are introduced before the Elasticsearch 9.0 release, users can opt-in for another ES|QL version by passing/setting the version explicitly or by changing the global default using `EsqlVersion.setDefault()`.
> Add ES|QL version support with its default value

- .buildkite/configure_signing.sh
- java-client-serverless/build.gradle.kts
This is a sample configuration to implement signing and publishing to maven central using a buildkite pipeline.
Note: The script will only work in buildkite. It will work as-it is without any changes there.
It's recomended to change use the https://github.com/elastic/vault-secrets-buildkite-plugin in the pipeline instead of the vault cli in the script. 
I tested the signing locally and it works, the publishing fails with:
```
* What went wrong:
Execution failed for task ':java-client-serverless:publishMavenPublicationToMavenCentralSnapshotRepository'.
> Failed to publish publication 'maven' to repository 'MavenCentralSnapshot'
> Could not PUT 'https://s01.oss.sonatype.org/content/repositories/snapshots/co/elastic/clients/elasticsearch-java-serverless/1.0.0-20231031-SNAPSHOT/maven-metadata. …
```
> Sample configuration for singing and publishing to maven central

- java-client/src/test/java/co/elastic/clients/documentation/getting_started/ConnectingTest.java
Without this line, the code hangs because the HttpClient thread keeps running indefinitely.
> [DOCS] Add transport.close() to connecting page

- java-client/src/main/java/co/elastic/clients/elasticsearch/_types/aggregations/Aggregate.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/_types/aggregations/AggregateBuilders.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/_types/aggregations/BoxPlotAggregate.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/_types/aggregations/TermsBucketBase.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/core/mtermvectors/MultiTermVectorsOperation.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/doc-files/api-spec.html
- java-client/src/main/java/co/elastic/clients/elasticsearch/nodes/info/NodeInfoScript.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/nodes/info/NodeInfoSettings.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/nodes/info/NodeInfoSettingsNetwork.java
Update to the generated code from the latest specification and code-generator. This includes https://github.com/elastic/elasticsearch-specification/pull/2597, which fixes https://github.com/elastic/elasticsearch-java/issues/558, fixes https://github.com/elastic/elasticsearch-java/issues/716, fixes https://github.com/elastic/elasticsearch-java/issues/783, fixes https://github.com/elastic/elasticsearch-java/issues/785, fixes https://github.com/elastic/elasticsearch-java/issues/707.
> FIxes from spec 2597

- docs/api-conventions/object-lifecycles.asciidoc
- docs/release-notes/release-highlights.asciidoc
- java-client/src/main/java/co/elastic/clients/ApiClient.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngester.java
- java-client/src/test/java/co/elastic/clients/documentation/getting_started/ConnectingTest.java
`ElasticsearchClient` and other client classes now implement `Closeable`, which closes the underlying `Transport` object.
> Make ApiClient and subclasses Closeable

- java-client/src/main/java/co/elastic/clients/transport/endpoints/BooleanEndpoint.java
4xx errors other than 404 should throw an exception and not return a valid `false` result.
Fixes #850
> Refine BooleanEndpoint so that 4xx status codes other than  404 are considered as errors

- java-client/src/main/java/co/elastic/clients/transport/endpoints/BooleanEndpoint.java
> [7.17] Refine BooleanEndpoint so that 4xx status codes other than 404 are considered as errors (#853)

- java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngester.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngesterTest.java
When the Bulk Ingester is configured in such a way that the number of external threads performing the `add` operation is much higher than  `maxConcurrentRequests` (usually more than 50 to 1), after completing all of the request but the last one, the Bulk Ingester stops. 
If there's a flusher thread, it will keep adding requests one by one, and sending them one by one: this is because ~95% of the external threads will get stuck while adding, and a `send` operation will only free one of those at a time. 
Replacing `signal()` with `signalAll()` to free the threads is a possible solution, but it's also expensive and considering this is an extreme case it would affect performances for every other case; so the chosen solution is to add another `signal()` after a successful `add` operation, …
> Addressing bulk ingester stuck threads

- java-client/src/main/java/co/elastic/clients/elasticsearch/doc-files/api-spec.html
- java-client/src/main/java/co/elastic/clients/elasticsearch/nodes/info/NodeInfoXpackSecurity.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/BehaviorsTest.java
> 7.17 - Node info http nullable

- docs/setup/open-telemetry.asciidoc
@szabosteve kindly did a review of the docs I wrote to accompany my native OpenTelemetry implementation in the ES Ruby client. I used many of the docs from this repo to write that one, so I'm applying some of the changes here as well.
Here is the commit from the ruby repo: https://github.com/elastic/elasticsearch-ruby/pull/2179/commits/bb7b6123bc154355d5631b4bfb3c6c62955c6a0c 
cc @AlexanderWert
> Otel docs updates

- catalog-info.yaml
- examples/esql-article/src/main/java/co/elastic/clients/esql/article/EsqlArticle.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/core/CountRequest.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/core/ExplainRequest.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/indices/ValidateQueryRequest.java
- java-client/src/main/java/co/elastic/clients/json/DelegatingJsonGenerator.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/transport/ElasticsearchTransportBase.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/EndpointBase.java
- java-client/src/main/java/co/elastic/clients/transport/endpoints/SimpleEndpoint.java
- java-client/src/test/java/co/elastic/clients/transport/TransportTest.java
- java-client/src/test/java/co/elastic/clients/transport/endpoints/SimpleEndpointTest.java
Allow requests that have all-optional properties to be serialized as an empty body (zero bytes) instead of an empty object (`{}`)
Some endpoints (e.g. `/_validate/query`) require this behavior and reject requests that have an empty object body. 
This is achieved by wrapping the body accessor in endpoint definitions using `EndpointBase.nonEmptyJsonObject(bodyGetter)`. This will be added to the relevant endpoints in the code generator.
> Allow requests to be serialized as nothing instead of an empty object

- java-client/src/test/java/co/elastic/clients/json/JsonpMappingExceptionTest.java
- java-client/src/test/java/co/elastic/clients/testkit/ModelTestCase.java
The JSON mappers used in tests are in strict mode and will reject unknown fields when deserializing objects. This was useful in the early days of the Java Client when the API spec was still in flux. We now have extensive validation for the API spec that catches these unknown fields.
This PR removes strict mode from test JSON mappers, so that they behave like regular applications.
> Run tests in non-strict JSON mode, like real applications

- java-client/src/main/java/co/elastic/clients/json/JsonEnums.java
The elasticsearch server sometimes accepts user strings as enums, ignoring the case of the letters, so the clients must parse json enums regardless of the case.
> Json enum case insensitive

- docs/reference/aggregations.md
- docs/reference/building-objects.md
- docs/reference/package-structure.md
- docs/reference/using-java-api-client.md
Follow up to #952 
When using cross-repo links, the path should be relative to the `docset.yml` not the full path within the repo ([updated docs-builder docs](https://elastic.github.io/docs-builder/syntax/links/#cross-repository-links)).
> [docs] Clean up cross-repo links

- docs/reference/_basic_authentication.md
- docs/reference/_encrypted_communication.md
- docs/reference/_timeouts.md
- docs/reference/java-rest-low-usage-initialization.md
- docs/reference/java-rest-low-usage-logging.md
- docs/reference/java-rest-low-usage-responses.md
- docs/reference/java-rest-low-usage-shading.md
Fix external links that incorrectly use `.md` instead of `.html`.
> [docs] Fix external links

- .ci/configure_signing.sh
- .ci/make.sh
- build.gradle.kts
- java-client/build.gradle.kts
- settings.gradle.kts
Using all in 1 nexus plugin for automatic release to maven central
> Maven central release with nexus plugin

- docs/reference/getting-started.md
- docs/reference/installation.md
- java-client/build.gradle.kts
- java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
- java-client/src/main/java/co/elastic/clients/json/SimpleJsonpMapper.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonProvider.java
- java-client/src/main/java/co/elastic/clients/json/jackson/JsonValueParser.java
- java-client/src/main/java/co/elastic/clients/json/jsonb/JsonbJsonpMapper.java
- java-client/src/test/java/co/elastic/clients/json/JsonpUtilsTest.java
- java-client/src/test/java/co/elastic/clients/testkit/ModelTestCase.java
Our docs illustrate/promote using Jackson as a `JsonMapper` implementation, and yet it was an optional dependency.
This PR makes Jackson the default implementation, and makes it a required dependency. It also updates all JSON-related libraries to their latest version.
> Use Jackson as the default JSON implementations, update libraries

- java-client/src/main/java/co/elastic/clients/transport/rest5_client/low_level/Rest5Client.java
- java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientTransport.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestClient.java
- java-client/src/test/java/co/elastic/clients/transport/ElasticsearchTransportConfigTest.java
Fixes the new client constructors that accept `java.net.URI` that were ignoring the path part. Also ensures all URIs have the same path, as RestClient and Rest5Client accept a single path prefix common to all nodes.
> Handle path prefixes when creating clients using URIs

- java-client/src/main/java/co/elastic/clients/elasticsearch/core/MsearchRequest.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/core/SearchRequest.java
- java-client/src/main/java/co/elastic/clients/elasticsearch/core/search/Hit.java
- java-client/src/main/java/co/elastic/clients/json/JsonpDeserializer.java
- java-client/src/main/java/co/elastic/clients/json/JsonpDeserializerBase.java
- java-client/src/test/java/co/elastic/clients/elasticsearch/model/BehaviorsTest.java
Generated output + unit test handling `matched_queries` as an actual array | map union. 
Generator reference: https://github.com/elastic/elastic-client-generator-java/pull/58
Fixes https://github.com/elastic/elasticsearch-java/issues/634
> Support include_names_queries_score

- docs/redirects.yml
https://github.com/elastic/elasticsearch-java/pull/988 needed these redirects -- adding them now.
> Add redirects to fix docs build errors

- docs/reference/getting-started.md
- docs/reference/setup/opentelemetry.md
Fixes image paths to work with docs-assembler.
Notes for the reviewer:
* I was not able to get images in reference, extend, or release-notes to work using the `:::{image}` syntax because it seems to resolve differently than the Markdown `![]()` syntax. We should address this in docs-builder, but in order to get images working as soon as possible, I've used Markdown syntax and left us a `TO DO` in a code comment to add back the `screenshot` class where applicable. 
* Can you please add the appropriate labels needed for backporting?
> [docs] Fix image paths for docs-assembler

- docs/reference/transport/rest-client/sniffer/maven_repository.md
- docs/reference/transport/rest-client/usage/maven.md
- docs/reference/transport/rest-client/usage/requests.md
Fixes various syntax and rendering errors that might include:
* Fixing broken images
* Hardcoding book-level substitution values
* Fixing incorrectly closed blocks (admonitions, tab sets, code blocks, dropdowns etc.)
* Fixing poorly migrated complex tables
* Fixing poorly migrated lists
* Fixing poorly migrated tab sets
* Removing inline text formatting from directive titles where they won't be rendered (for example, inline `code` formatting in dropdown titles)
* Specifying if a version is trying to communicate if a feature was added, deprecated, or coming (for example, during migration `deprecated:[8.15.0]` became `[8.15.0]`, which doesn't give any information about _what_ happened in 8.15.0)
* Fixing nested dropdowns / definition lists
* Fixing poorly migrated footnotes
* Updating …
> [docs] Fix various syntax and rendering errors 

- docs/reference/index.md
The file `docs/reference/migrate-hlrc.md` was deleted in https://github.com/elastic/elasticsearch-java/pull/988/ so we lost a mapping for the old `current` URL: https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/migrate-hlrc.html. We don't need the content of that old page in the v3 docs, so I mapped it to the Java client docs index page.
> [Docs] Add mapping for deleted file

- java-client/build.gradle.kts
> Fully targeting java 8

- java-client/build.gradle.kts
Multiple fixes for gradle build:
- Adds back the commons-logging dependency (previously transitive from rest-client)
- Removes code that synchronized the rest-client version (no longer needed)
- Updates rest-client (optional) version to current minor version (9.0.0)
- Updates httpclient5 dependency from 5.4 to 5.4.4 because of a [security issue](https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5/5.4)
> Fix dependencies + pom building

- java-client/build.gradle.kts
Partially backporting https://github.com/elastic/elasticsearch-java/pull/1010 to 8.x branches, using the matching minor version for each version
> Using fixed minor version of rest-client - 8

- docs/reference/javadoc-source-code.md
Replaced stale snapshots link with link to latest Javadoc.
[Preview](https://docs-v3-preview.elastic.dev/elastic/elasticsearch-java/pull/1014/reference/javadoc-source-code)
via Slack
> [Docs] Fix broken Javadoc link

- java-client/src/main/java/co/elastic/clients/transport/rest_client/MultiBufferEntity.java
As reported in #1003, it appears that the list of Buffers in `MultiBufferEntity` can be accessed by multiple threads in case of frequent connection exceptions, by calling the functions `init()` and `produceContent()` at the same time. This PR introduces a local iterator in `init()` so that it will not try to call `next()` on an empty iterable.
> Avoid concurrent access to multibuffer entity iterator

- java-client/build.gradle.kts
- java-client/src/main/java/co/elastic/clients/transport/instrumentation/OpenTelemetryForElasticsearch.java
- java-client/src/test/java/co/elastic/clients/transport/instrumentation/OpenTelemetryForElasticsearchTest.java
Replaced the alpha dependency with the stable release, followed the [migration guide](https://opentelemetry.io/docs/specs/semconv/non-normative/db-migration/) to replace the old constants with the stable ones, using the ones from the library where possible.
> Using stable Otel conventions

- java-client/src/main/java/co/elastic/clients/transport/rest5_client/low_level/Rest5ClientBuilder.java
Making more http client configurations available from the Rest5Builder
> Added more setters in Rest5Builder

- java-client/src/main/java/co/elastic/clients/transport/endpoints/EndpointBase.java
GetAliasesResponse is a special case because it can return both an exception and the actual response, in case 2 aliases, 1 present and 1 missing, are added to GetAliasesRequest:
```json
{
"error": "alias [test2] missing",
"status": 404,
"example-index": {
"aliases": {
"test": {}
}
}
}
```
The error deserializer doesn't recognize `example-index` (or any other custom field), and so a TransportException is thrown. This PR adds a default case to the error response deserializer so that any additional field is tentatively deserialized into the `metadata` map of `ErrorCause`.
So the json above would still the client throw an ElasticsearchException, since there's a 404 error, and the rest of the information would be found in `metadata` like so:
```java
try{
client.indices().getAlias(a -> …
```
> Fix GetAliasResponse bug

- java-client/src/main/java/co/elastic/clients/transport/rest5_client/Rest5ClientOptions.java
- java-client/src/main/java/co/elastic/clients/transport/rest5_client/SafeResponseConsumer.java
- java-client/src/test/java/co/elastic/clients/transport/rest5_client/low_level/SafeResponseConsumerTest.java
As reported in #1046, apache http client 5 still has issues with some kind of errors terminating the IoReactor indefinitely, which we try to avoid. Reintroducing the SafeResponseConsumer, which wraps Errors in RuntimeExceptions.
> Safe response consumer for rest5client

- docs/release-notes/index.md
label 9.0.1 points to release note version 9.1.0, so corrected the label
> Update index.md to point correct version number

- java-client/src/main/java/co/elastic/clients/transport/ElasticsearchTransportBase.java
- java-client/src/main/java/co/elastic/clients/transport/rest5_client/Rest5ClientOptions.java
- java-client/src/main/java/co/elastic/clients/transport/rest5_client/low_level/BufferedByteConsumer.java
This provides a workaround for a bug which affects empty body requests when sent with the Rest5Client configured to support http2.
The issue was introduced server side by https://github.com/elastic/elasticsearch/pull/129302 and results in empty body requests causing the following exception: `Invalid media-type value on headers [Accept, Content-Type]`.
(bonus: log fixes for Rest5Client)
> Http2 bug workaround

- README.md
- docs/reference/transport/rest-client/sniffer/usage.md
- docs/reference/transport/rest5-client/config/basic_authentication.md
- docs/reference/transport/rest5-client/config/encrypted_communication.md
- docs/reference/transport/rest5-client/config/index.md
- docs/reference/transport/rest5-client/config/node_selector.md
- docs/reference/transport/rest5-client/config/number_of_threads.md
- docs/reference/transport/rest5-client/config/other_authentication_methods.md
- docs/reference/transport/rest5-client/config/others.md
- docs/reference/transport/rest5-client/config/timeouts.md
- docs/reference/transport/rest5-client/sniffer/index.md
- docs/reference/transport/rest5-client/usage/index.md
- docs/reference/transport/rest5-client/usage/initialization.md
- docs/reference/transport/rest5-client/usage/logging.md
- docs/reference/transport/rest5-client/usage/requests.md
- docs/reference/transport/rest5-client/usage/responses.md
Needed for https://github.com/elastic/docs-builder/pull/1899
docs-builder can only handle mapped_pages to `/guide`
> Remove invalid `mapped_pages`

- java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonBuffer.java
- java-client/src/test/java/co/elastic/clients/json/jackson/JacksonJsonBufferTest.java
Ref. https://github.com/elastic/elasticsearch-java/issues/866 Overriding toString function to print readable JSON pulled in from JacksonJsonBuffer.
> 866 - JacksonJsonBuffer - Overriding toString
