README.md

This PR just adds a section to the readme about how to configure GitHub packages when using maven instead of gradle

Add information for setup with maven

---

docs/installation.asciidoc

Backports https://github.com/elastic/elasticsearch-java/pull/14

[7.x][DOCS] Fixes typo

---

docs/installation.asciidoc

Backports https://github.com/elastic/elasticsearch-java/pull/14

[7.15][DOCS] Fixes typo

---

docs/connecting.asciidoc
docs/index.asciidoc
docs/installation.asciidoc

This PR adds some intro text to the index file and changes the code snippet attributes so the snippets resolve correctly in HTML.

[DOCS] Adds intro text to the index file, changes snippet attributes

---

docs/introduction.asciidoc

This PR backports the following changes to the 7.x branch: [DOCS] Updates the link in Introduction that points to LLRC #29

[7.x][DOCS] Updates the link in Introduction that points to LLRC.

---

docs/api-conventions.asciidoc
docs/connecting.asciidoc
docs/index-local.asciidoc
docs/index.asciidoc
docs/installation.asciidoc
docs/introduction.asciidoc
docs/local/README.md
docs/local/elasticsearch/docs/java-rest/low-level/index.asciidoc
docs/migrate.asciidoc
java-client/src/test/java/co/elastic/clients/documentation/ApiConventionsTest.java

Co-authored-by: István Zoltán Szabó <istvan.szabo@elastic.co>
Backport of PR #52

[docs] Update with the latest changes and use compilable examples (#52)

---

java-client/src/main/java/co/elastic/clients/json/JsonpDeserializerBase.java
java-client/src/test/java/co/elastic/clients/elasticsearch/model/BuiltinTypesTest.java

Accept null values in arrays

---

java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java
java-client/src/test/java/co/elastic/clients/elasticsearch/spec_issues/SpecIssuesTest.java
java-client/src/test/resources/co/elastic/clients/elasticsearch/spec_issues/issue-0087-request.json
java-client/src/test/resources/co/elastic/clients/elasticsearch/spec_issues/issue-0087-response.json
java-client/src/test/resources/co/elastic/clients/elasticsearch/spec_issues/issue-0088-response.json

Add tests for #87 and #88

---

java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java
java-client/src/test/java/co/elastic/clients/elasticsearch/spec_issues/SpecIssuesTest.java
java-client/src/test/resources/co/elastic/clients/elasticsearch/spec_issues/issue-0087-request.json
java-client/src/test/resources/co/elastic/clients/elasticsearch/spec_issues/issue-0087-response.json
java-client/src/test/resources/co/elastic/clients/elasticsearch/spec_issues/issue-0088-response.json

Backports the following commits to 7.17:
- Add tests for #87 and #88 (#126)

[7.17] Add tests for #87 and #88 (#126)

---

config/forbidden-apis.txt
java-client/build.gradle.kts
java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonProvider.java
java-client/src/main/java/co/elastic/clients/json/jackson/JsonValueParser.java
java-client/src/main/java/co/elastic/clients/json/jsonb/JsonbJsonpMapper.java
java-client/src/main/java/co/elastic/clients/util/AllowForbiddenApis.java
java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/ParsingTests.java
java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/containers/SomeUnionTest.java
java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/inheritance/InheritanceTest.java
java-client/src/test/java/co/elastic/clients/elasticsearch/json/JsonpUtilsTest.java

Backport 8389a694c022cb91de2307f65fe8a79d7e843c1e from #173

Fallback to current class if loading a Jsonp provider using ServiceLoader fails (#173)

---

docs/api-conventions/exceptions.asciidoc
docs/api-conventions/index.asciidoc
docs/index.asciidoc
docs/troubleshooting/index.asciidoc
docs/troubleshooting/missing-required-property.asciidoc
docs/usage/aggregations.asciidoc

Explain the temporary workaround to disable required property checks.

Add docs about MissingRequiredPropertyException

---

java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpGenerator.java
java-client/src/test/java/co/elastic/clients/json/jackson/JacksonJsonpGeneratorTest.java

[7.17] Fix booleans in JacksonJsonpGenerator and add tests (#327)

---

java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpGenerator.java
java-client/src/test/java/co/elastic/clients/json/jackson/JacksonJsonpGeneratorTest.java

[8.3] Fix booleans in JacksonJsonpGenerator and add tests (#327)

---

docs/api-conventions/variant-types.asciidoc
java-client/src/test/java/co/elastic/clients/documentation/DocTestsTransport.java
java-client/src/test/java/co/elastic/clients/documentation/api_conventions/ApiConventionsTest.java

Add docs for plugin-defined custom variants. See PR #370.

Add documentation for plugin-defined custom variants

---

java-client/src/main/java/co/elastic/clients/elasticsearch/core/CreateRequest.java
java-client/src/main/java/co/elastic/clients/elasticsearch/core/IndexRequest.java
java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
java-client/src/main/java/co/elastic/clients/transport/Endpoint.java
java-client/src/main/java/co/elastic/clients/transport/endpoints/BinaryEndpoint.java
java-client/src/main/java/co/elastic/clients/transport/endpoints/BooleanEndpoint.java
java-client/src/main/java/co/elastic/clients/transport/endpoints/DelegatingJsonEndpoint.java
java-client/src/main/java/co/elastic/clients/transport/endpoints/EndpointBase.java
java-client/src/main/java/co/elastic/clients/transport/endpoints/SimpleEndpoint.java
java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientTransport.java
java-client/src/main/java/co/elastic/clients/util/BinaryData.java
java-client/src/main/java/co/elastic/clients/util/ByteArrayBinaryData.java
java-client/src/main/java/co/elastic/clients/util/ContentType.java
java-client/src/test/java/co/elastic/clients/documentation/usage/IndexingBulkTest.java
java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java
java-client/src/test/java/co/elastic/clients/transport/endpoints/BooleanEndpointTest.java

[7.17] Allow unparsed binary data to be used for ingestion (#508)

---

java-client/src/main/java/co/elastic/clients/elasticsearch/_types/analysis/Analyzer.java
java-client/src/test/java/co/elastic/clients/elasticsearch/model/VariantsTest.java

[7.17] Add default variant to Analyzer (#522)

---

java-client/src/main/java/co/elastic/clients/elasticsearch/_types/query_dsl/BoolQuery.java
java-client/src/test/java/co/elastic/clients/elasticsearch/model/CodeAdditionsTests.java

Add BooleanQuery.hasClauses()

---

java-client/src/main/java/co/elastic/clients/elasticsearch/_types/query_dsl/BoolQuery.java
java-client/src/test/java/co/elastic/clients/elasticsearch/model/CodeAdditionsTests.java

[8.7] Add BooleanQuery.hasClauses() (#525)

---

java-client/src/main/java/co/elastic/clients/elasticsearch/_types/query_dsl/BoolQuery.java
java-client/src/test/java/co/elastic/clients/elasticsearch/model/CodeAdditionsTests.java

[7.17] Add BooleanQuery.hasClauses() (#525)

---

java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/IngesterOperation.java
java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngesterTest.java

[8.8] Add pipeline setup to index and create operations (#587)

---

java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngester.java
java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngesterTest.java

[7.17] Add validation to BulkIngester settings (#602)

---

java-client-serverless/build.gradle.kts
java-client/build.gradle.kts

Upgrade Parsson to 1.0.5

---

java-client-serverless/build.gradle.kts
java-client/build.gradle.kts

[8.12] Upgrade Parsson from 1.0.0 to 1.0.5 (#722)

---

java-client/build.gradle.kts

[7.17] Upgrade Parsson from 1.0.0 to 1.0.5 (#722)

---

docs/getting-started/installation.asciidoc
java-client/build.gradle.kts

[7.17] Update Jackson version (#768)

---

java-client/src/main-flavored/java/co/elastic/clients/transport/VersionInfo.java

Updated version info, closes #717

Version info update

---

java-client/src/main-flavored/java/co/elastic/clients/transport/VersionInfo.java

Update version info

---

docs/reference/aggregations.md

Related to https://github.com/elastic/elasticsearch/pull/125663
Removes reliance on temporary redirects in the elasticsearch repo.

[docs] Remove reliance on temporary redirects

---

java-client/build.gradle.kts

To avoid issues like #995 in the future

Make sure to always target java 17

---

java-client/src/main/java/co/elastic/clients/transport/rest5_client/low_level/BufferedByteConsumer.java

Fixes https://github.com/elastic/elasticsearch-java/issues/1054

Rest5Client consumer limit check fix

---

java-client/src/main/java/co/elastic/clients/elasticsearch/_types/SortOptions.java
java-client/src/test/java/co/elastic/clients/elasticsearch/model/SerializationTest.java

Regenerating SortOptions after generator changes provided by @swallez. Fixes #573

Sort option fix
